Repository numba/llvmlite, pull requests merged in 2018-10, with the labels that each got.

#403 Add shutdown detection to ObjectRef __del__ method.
  llvmlite/binding/ffi.py
Labels: Ready for Review

#394 Enable IntelJIT events for LLVM for VTune support
  conda-recipes/llvmdev/bld.bat
  conda-recipes/llvmdev/build.sh
  conda-recipes/llvmdev/meta.yaml
  conda-recipes/llvmdev_manylinux1/bld.bat
  conda-recipes/llvmdev_manylinux1/build.sh
  ffi/executionengine.cpp
  llvmlite/binding/executionengine.py
Labels: BuildFarm Passed

#404 Move to LLVM 7
  README.rst
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  conda-recipes/0001-Transforms-Add-missing-header-for-InstructionCombini.patch
  conda-recipes/D47188-svml-VF.patch
  conda-recipes/D47188-svml.patch
  conda-recipes/llvmdev/meta.yaml
  conda-recipes/llvmdev_manylinux1/meta.yaml
  conda-recipes/llvmlite/meta.yaml
  docs/source/admin-guide/install.rst
  docs/source/conf.py
  docs/source/user-guide/ir/index.rst
  ffi/build.py
  llvmlite/tests/test_binding.py
Labels: BuildFarm Passed, Ready for Review

#409 Use native cmake on armv7l
  conda-recipes/llvmdev/meta.yaml
Labels: Ready for Review

#408 Update LLVM 7 config for SVML.
  buildscripts/incremental/setup_conda_environment.sh
  ffi/CMakeLists.txt
  ffi/build.py
Labels: Ready for Review
