Repository numba/llvmlite, pull requests merged in 2019-05, with the labels that each got.

#478 Upgrade to llvm8
  README.rst
  buildscripts/azure/azure-windows.yml
  buildscripts/incremental/setup_conda_environment.cmd
  buildscripts/incremental/setup_conda_environment.sh
  conda-recipes/0001-Revert-Limit-size-of-non-GlobalValue-name.patch
  conda-recipes/0001-RuntimeDyld-Add-test-case-that-was-accidentally-left.patch
  conda-recipes/0001-RuntimeDyld-Fix-a-bug-in-RuntimeDyld-loadObjectImpl-.patch
  conda-recipes/D47188-svml-VF.patch
  conda-recipes/llvmdev/bld.bat
  conda-recipes/llvmdev/build.sh
  conda-recipes/llvmdev/meta.yaml
  conda-recipes/llvmdev/test_cfg_dot.py
  conda-recipes/llvmdev_manylinux1/meta.yaml
  conda-recipes/llvmlite/meta.yaml
  ffi/CMakeLists.txt
  ffi/build.py
  llvmlite/tests/test_binding.py
Labels: BuildFarm Passed, Ready for merge

#460 LLVM 7 changed memset intrinsic signature, adjust it
  llvmlite/ir/module.py
  llvmlite/tests/test_ir.py
Labels: Ready for merge

#483 Depend on enum34 using PEP 508 environment markers
  setup.py
Labels: Ready for Review, enhancement

#487 Update changelog for 0.29.0
  CHANGE_LOG
Labels: Ready for Review
