Repository numba/llvmlite, pull requests merged in 2019-09, with the labels that each got.

#513 Remove restriction on sphinx version from Anaconda distro
  buildscripts/incremental/setup_conda_environment.sh
Labels: Ready for merge

#470 Fix leak on string returning APIs.
  ffi/dylib.cpp
  ffi/executionengine.cpp
  ffi/value.cpp
  llvmlite/binding/ffi.py
  llvmlite/binding/value.py
Labels: Ready for merge

#474 Update docs
  docs/source/conf.py
Labels: Ready for merge

#491 Fix incorrect hierarchy in the documentation for ir.Constant.
  docs/source/user-guide/ir/values.rst
Labels: Ready for merge

#502 Add -fPIC flag for manylinux1 wheel building
  ffi/Makefile.linux
  setup.py
Labels: Ready for Review

#509 Add Half-Precision Type
  docs/source/user-guide/ir/types.rst
  llvmlite/ir/builder.py
  llvmlite/ir/types.py
  llvmlite/llvmpy/core.py
  llvmlite/tests/test_ir.py
  llvmlite/tests/test_valuerepr.py
Labels: Ready for merge

#511 Deprecate the use of memset/memcpy with alias
  docs/source/conf.py
  docs/source/user-guide/deprecation.rst
  docs/source/user-guide/index.rst
Labels: Ready for merge

#512 fix for block labels which contain "interesting" characters
  llvmlite/ir/values.py
  llvmlite/tests/test_binding.py
Labels: Ready for merge

#510 Add fp16 Intrinsics
  llvmlite/ir/builder.py
  llvmlite/ir/module.py
  llvmlite/tests/test_ir.py
Labels: Waiting on CI
