Repository numba/llvmlite, pull requests merged in 2020-03, with the labels that each got.

#547 Permit building on Visual Studio 2017
  ffi/build.py
Labels: Ready for merge

#549 Miscalled method and missing parameter in the documentation
  docs/source/user-guide/ir/ir-builder.rst
Labels: Ready for merge, doc, enhancement

#552 Add paragraph on installing from sdist and on non-traditional platforms.
  docs/source/admin-guide/install.rst
Labels: Ready for merge, doc

#555 travis: Cleanup
  .travis.yml
Labels: Ready for merge

#558 update install docs
  docs/source/admin-guide/install.rst
Labels: Ready for merge

#556 binding: Allow empty features list
  llvmlite/binding/targets.py
  llvmlite/tests/test_binding.py
Labels: BuildFarm Passed, Ready for merge

#560 ENH: Better error message
  ffi/build.py
Labels: Ready for merge

#551 Remove python 2, python < 3.6, fix up, add flake8
  .flake8
  .travis.yml
  AUTHORS
  README.rst
  appveyor.yml
  azure-pipelines.yml
  buildscripts/azure/azure-linux-macos.yml
  buildscripts/azure/azure-windows.yml
  buildscripts/incremental/setup_conda_environment.sh
  buildscripts/manylinux1/README.md
  conda-recipes/llvmlite/meta.yaml
  docs/source/admin-guide/install.rst
  docs/source/contributing.rst
  docs/source/user-guide/ir/types.rst
  llvmlite/__init__.py
  llvmlite/binding/__init__.py
  llvmlite/binding/analysis.py
  llvmlite/binding/common.py
  llvmlite/binding/context.py
  llvmlite/binding/dylib.py
  llvmlite/binding/executionengine.py
  llvmlite/binding/ffi.py
  llvmlite/binding/initfini.py
  llvmlite/binding/linker.py
  llvmlite/binding/module.py
  llvmlite/binding/object_file.py
  llvmlite/binding/options.py
  llvmlite/binding/passmanagers.py
  llvmlite/binding/targets.py
  llvmlite/binding/transforms.py
  llvmlite/binding/value.py
  llvmlite/ir/_utils.py
  llvmlite/ir/builder.py
  llvmlite/ir/context.py
  llvmlite/ir/instructions.py
  llvmlite/ir/module.py
  llvmlite/ir/transforms.py
  llvmlite/ir/types.py
  llvmlite/ir/values.py
  llvmlite/llvmpy/core.py
  llvmlite/llvmpy/passes.py
  llvmlite/six.py
  llvmlite/tests/__init__.py
  llvmlite/tests/__main__.py
  llvmlite/tests/customize.py
  llvmlite/tests/test_binding.py
  llvmlite/tests/test_ir.py
  llvmlite/tests/test_llvmpy.py
  llvmlite/tests/test_valuerepr.py
  llvmlite/utils.py
Labels: Ready for merge

#561 Update changelog for 0.32.0rc1
  CHANGE_LOG
Labels: Ready for Review
