Repository numba/llvmlite, pull requests merged in 2021-01, with the labels that each got.

#687 Cleanup public CI configuration and badge
  .travis.yml
  README.rst
  appveyor.yml
Labels: 3 - Ready for Review

#682 slight rearrangement of intro
  README.rst
Labels: 5 - Ready to merge, doc

#689 fixup azure badge to point at master branch
  README.rst
Labels: 5 - Ready to merge

#690 Callback to track when the llvm lock is acquired and released
  docs/source/user-guide/binding/index.rst
  docs/source/user-guide/binding/misc.rst
  llvmlite/binding/ffi.py
  llvmlite/tests/test_binding.py
Labels: 5 - Ready to merge

#670 Llvmdev windows 10
  .gitattributes
  conda-recipes/llvmdev/bld.bat
  conda-recipes/llvmdev/build.sh
  conda-recipes/llvmdev/meta.yaml
  conda-recipes/partial-testing.patch
Labels: 5 - Ready to merge

#673 use build 2 on windows
  conda-recipes/llvmlite/meta.yaml
Labels: 5 - Ready to merge

#685 Added fneg instruction
  docs/source/user-guide/ir/ir-builder.rst
  llvmlite/ir/builder.py
  llvmlite/tests/test_ir.py
Labels: 5 - Ready to merge, enhancement
