Repository numba/llvmlite, pull requests merged in 2022-01, with the labels that each got.

#806 Bump to v0.39.0dev
  CHANGE_LOG
Labels: 5 - Ready to merge

#754 manylinux2014 aarch64 wheels with system compilers
  buildscripts/manylinux2014/configure_conda.sh
  conda-recipes/llvmdev_manylinux2014/meta.yaml
Labels: 5 - Ready to merge

#760 add support for attaching metadata to global variables
  docs/source/user-guide/ir/values.rst
  llvmlite/ir/values.py
  llvmlite/tests/test_ir.py
Labels: 5 - Ready to merge

#786 Update Windows and OSX CI images.
  azure-pipelines.yml
Labels: 5 - Ready to merge

#803 llvm::Module::GetSourceFileName
  docs/source/user-guide/binding/modules.rst
  ffi/module.cpp
  llvmlite/binding/module.py
  llvmlite/tests/test_binding.py
Labels: 5 - Ready to merge

#809 Update CHANGE_LOG for 0.38.0
  CHANGE_LOG
Labels: 3 - Ready for Review

#815 update local references
  .github/ISSUE_TEMPLATE/bug_report.md
  README.rst
  docs/source/admin-guide/install.rst
Labels: 5 - Ready to merge

#801 Update ffi.py
  llvmlite/binding/ffi.py
Labels: BuildFarm Passed, 5 - Ready to merge

#807 Exclude ExecutionEngine tests on linux 32
  conda-recipes/llvmdev_manylinux2014/build.sh
Labels: 5 - Ready to merge
