Repository numba/llvmlite, pull requests merged in 2022-08, with the labels that each got.

#874 Adding zlib as dependency for aarch64
  conda-recipes/llvmlite/meta.yaml
Labels: 3 - Ready for Review

#752 Skip test if libm is not found.
  llvmlite/tests/test_binding.py
Labels: BuildFarm Passed, 5 - Ready to merge

#865 Move Azure to use macos-11.
  azure-pipelines.yml
Labels: 3 - Ready for Review

#827 Add more LLVM pass bindings
  azure-pipelines.yml
  ffi/passmanagers.cpp
  llvmlite/binding/passmanagers.py
  llvmlite/tests/test_binding.py
Labels: 5 - Ready to merge
