Repository numba/llvmlite, pull requests merged in 2023-06, with the labels that each got.

#950 Fix incorrect `byval` and other attributes on LLVM 14
  llvmlite/binding/analysis.py
  llvmlite/ir/instructions.py
  llvmlite/ir/values.py
  llvmlite/tests/test_ir.py
Labels: 4 - Waiting on reviewer

#957 0.40.1 rel cherry pick
  CHANGE_LOG
  conda-recipes/llvm14-svml.patch
  conda-recipes/llvmdev/meta.yaml
  conda-recipes/llvmlite/meta.yaml
  llvmlite/binding/analysis.py
  llvmlite/binding/passmanagers.py
  llvmlite/ir/instructions.py
  llvmlite/ir/values.py
  llvmlite/tests/test_binding.py
  llvmlite/tests/test_ir.py
Labels: 3 - Ready for Review, Pending BuildFarm

#960 add various bullets to release checklists and sync
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
Labels: 3 - Ready for Review

#966 build: support building on GNU/Hurd
  ffi/build.py
  setup.py
Labels: 5 - Ready to merge

#969 update changelog on main for v0.40.1
  CHANGE_LOG
Labels: 3 - Ready for Review

#959 Remove support for LLVM < 14
  conda-recipes/llvm11-0001-Revert-Limit-size-of-non-GlobalValue-name.patch
  conda-recipes/llvm11-consecutive_registers.patch
  conda-recipes/llvm11-expect-fastmath-entrypoints-in-add-TLI-mappings.ll.patch
  conda-recipes/llvm11-intel-D47188-svml-VF.patch
  conda-recipes/llvm11-lto-static.patch
  conda-recipes/llvm11-partial-testing.patch
  conda-recipes/llvm12-0001-Revert-Limit-size-of-non-GlobalValue-name.patch
  conda-recipes/llvm12-consecutive_registers.patch
  conda-recipes/llvm12-lto-static.patch
  conda-recipes/llvm13-lto-static.patch
  conda-recipes/llvmdev/bld.bat
  conda-recipes/llvmdev/build.sh
  conda-recipes/llvmdev_manylinux2014/build.sh
  docs/source/conf.py
  ffi/build.py
  ffi/passmanagers.cpp
  ffi/targets.cpp
  ffi/value.cpp
  llvmlite/binding/passmanagers.py
  llvmlite/ir/values.py
  llvmlite/tests/test_ir.py
Labels: Pending BuildFarm, BuildFarm Passed, 5 - Ready to merge, highpriority

#958 fixup LLVM versions in version compat table
  README.rst
Labels: 5 - Ready to merge, doc

#896 drop upper limit on Python for conda recipe
  conda-recipes/llvmlite/meta.yaml
Labels: 5 - Ready to merge
