Repository numba/llvmlite, pull requests merged in 2023-11, with the labels that each got.

#1006 Release Notes 0.41.1 for main
  CHANGE_LOG
Labels: 3 - Ready for Review

#1007 update release checklists post 0.41.1
  .github/ISSUE_TEMPLATE/first_rc_checklist.md
  .github/ISSUE_TEMPLATE/sub_rc_checklist.md
Labels: 3 - Ready for Review

#1012 conda-recipe cleanups
  conda-recipes/llvmlite/bld.bat
  conda-recipes/llvmlite/meta.yaml
  llvmlite/tests/test_binding.py
Labels: 3 - Ready for Review

#1014 Fix conda-recipe syntax errors from #1012
  conda-recipes/llvmlite/meta.yaml
Labels: 3 - Ready for Review

#1010 Python 3.12
  README.rst
  conda-recipes/llvmlite/bld.bat
  setup.py
Labels: 5 - Ready to merge, 3.12

#1005 Remove suggestion that add_global_mapping() is unused
  llvmlite/binding/executionengine.py
Labels: 5 - Ready to merge
