Repository numba/llvmlite, pull requests merged in 2025-08, with the labels that each got.

#1246 gha/fix artifact usage manylinux wheels
  .github/workflows/llvmlite_linux-64_wheel_builder.yml
  .github/workflows/llvmlite_linux-aarch64_wheel_builder.yml
  buildscripts/manylinux/build_llvmlite.sh
Labels: 5 - Ready to merge

#1250 Fix pass timing logic to stop printing to stdout.
  ffi/newpassmanagers.cpp
Labels: 5 - Ready to merge

#1259 update osx-64 sdk on recipes and CI scripts to use MacOSX10.15 SDK
  .github/workflows/llvmdev_build.yml
  buildscripts/github/MacOSX10.10.sdk.checksum
  buildscripts/github/MacOSX10.15.sdk.checksum
  buildscripts/github/setup_platform.sh
  conda-recipes/llvmdev/conda_build_config.yaml
  conda-recipes/llvmdev_for_wheel/conda_build_config.yaml
  conda-recipes/llvmlite/build.sh
  conda-recipes/llvmlite/conda_build_config.yaml
Labels: 3 - Ready for Review

#1267 adding llvm20 docs
  docs/source/user-guide/index.rst
  docs/source/user-guide/llvm20.rst
Labels: 4 - Waiting on reviewer

#1268 Release 0.45: `CHANGE_LOG`
  CHANGE_LOG
Labels: 3 - Ready for Review
