Repository numba/llvmlite, pull requests merged in 2025-05, with the labels that each got.

#1211 gha/fix llvmlite linux workflows for version tags
  .github/workflows/llvmlite_linux-64_wheel_builder.yml
  .github/workflows/llvmlite_linux-arm64_wheel_builder.yml
Labels: 4 - Waiting on CI

#1209 remove singular clang-format check based on ubuntu/apt
  azure-pipelines.yml
Labels: 5 - Ready to merge

#1213 unify clang format check
  azure-pipelines.yml
  buildscripts/azure/azure-linux-macos.yml
Labels: 5 - Ready to merge

#1217 gha/refactor llvmlite win-64 workflows
  .github/workflows/llvmlite_win-64_conda_builder.yml
  .github/workflows/llvmlite_win-64_wheel_builder.yml
  buildscripts/github/validate_win-64_wheel.py
Labels: 5 - Ready to merge

#1216 gha/refactor llvmlite osx wheel workflows
  .github/workflows/llvmlite_osx-64_wheel_builder.yml
  .github/workflows/llvmlite_osx-arm64_wheel_builder.yml
  buildscripts/github/patch_osx-64_wheel.sh
  buildscripts/github/validate_osx-64_wheel.sh
Labels: 5 - Ready to merge

#1215 gha/add llvmlite linux-arm64 conda builder
  .github/workflows/llvmlite_linux-arm64_conda_builder.yml
Labels: 5 - Ready to merge

#1195 gha/add llvmlite osx-arm64 conda builder
  .github/workflows/llvmlite_osx-arm64_conda_builder.yml
Labels: 5 - Ready to merge

#1223 fix/revert gha recipe changes
  .github/workflows/llvmlite_osx-64_conda_builder.yml
  conda-recipes/llvmdev/conda_build_config.yaml
  conda-recipes/llvmdev_for_wheel/conda_build_config.yaml
  conda-recipes/llvmlite/conda_build_config.yaml
Labels: BuildFarm Passed, 5 - Ready to merge
