Repository numba/llvmlite, pull requests merged in 2025-02, with the labels that each got.

#1143 remove release.yml -- it's stale and outdated
  .github/workflows/release.yml
  buildscripts/github/config.toml
  buildscripts/github/install_llvmdev.ps1
  buildscripts/github/install_llvmdev.sh
Labels: 5 - Ready to merge

#1141 refactor llvmdev win builder
  .github/workflows/llvmdev_win_builder.yml
Labels: 5 - Ready to merge

#1144 Refactor recipe build flows
  .github/workflows/llvmdev_build.yml
  .github/workflows/llvmdev_linux-64_conda_builder.yml
  .github/workflows/llvmdev_win-64_conda_builder.yml
  .github/workflows/llvmdev_win_builder.yml
  .github/workflows/llvmlite_win-64_conda_builder.yml
  buildscripts/github/llvmdev_evaluate.py
Labels: 2 - In Progress

#1146 Extend pre-commit config
  .pre-commit-config.yaml
  renovate.json
  run_coverage.py
  runtests.py
  setup.py
Labels: 3 - Ready for Review

#1151 fix flake8 issues
  buildscripts/github/llvmdev_evaluate.py
Labels: 5 - Ready to merge

#1150 enable running workflow as part of pull-request
  .github/workflows/llvmlite_win-64_conda_builder.yml
Labels: 5 - Ready to merge

#1149 Rename llvmdev manylinux
  .github/workflows/llvmdev_build.yml
  buildscripts/github/llvmdev_evaluate.py
  buildscripts/manylinux/README.md
  buildscripts/manylinux/build_llvmdev.sh
  conda-recipes/llvmdev_for_wheel/bld.bat
  conda-recipes/llvmdev_for_wheel/build.sh
  conda-recipes/llvmdev_for_wheel/conda_build_config.yaml
  conda-recipes/llvmdev_for_wheel/meta.yaml
Labels: 3 - Ready for Review

#1152 adding pre-commit workflow
  .github/workflows/pre-commit.yml
Labels: 3 - Ready for Review

#1154 execute dist tests for linux-64 conda pkgs via Azure
  azure-pipelines.yml
  buildscripts/incremental/test.sh
  llvmlite/tests/test_binding.py
Labels: 5 - Ready to merge
